### ISSUE TITLE
Für 2.0 - Wünsche / Anregungen bitte hier

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/pdfout#10]
- [ ] Hilfsfunktionen
- [x] Beispiele

**Comment by alexplusde** [comment]
Settings-Seite sollte alle Optionen, die bisher im Template-Beispiel angegeben ist, beinhalten, sowie die Pfad-Option mit einschließen. https://github.com/FriendsOfREDAXO/pdfout/issues/2

Ein Auto-Modus könnte sich ggf. direkt einklinken beim Parameter pdf=1, sodass ein extra Template überflüssig wird.

**Comment by skerbis** [comment]
@alexplusde problematisch wird ein „Automodus“ bei den BildUrls

**Comment by cukabeka** [comment]
denke auch, dass ein pdf=1 -Trigger eher zu Problemen führen könnte. IMHO ist das manuell pro Fall zu Lösen und vom Aufwand her vertretbar.

**Comment by skerbis** [comment]
Bleibt erstmal alles wie es ist. Wenn jemand Ideen hat, gerne wieder öffnen.
