### ISSUE TITLE
Externe Links  in pdfOut 1.3.0 fehlerhaft

### ISSUE THREAD

**Issue by brandes-webdesign** [FriendsOfREDAXO/pdfout#17]
Alle Links werden in pdfOut 1.3.0 falsch verändert.

Es betrifft jegliche Links (wie z.B. http://domain.de/kontakt.html) und sogar welche mit mailto:info@domain.de.

Das hier kommt immer raus:
http://www.domain.de/þÿ
bzw.
http://www.domain.de/%C3%BE%C3%BF

Liegt vermutlich am vendor update 0.8.1 ???

Redaxo Version ist 5.4.0.
PHP Version 7.0 oder 5.6 ist egal, der Fehler tritt immer auf.

**Comment by brandes-webdesign** [comment]
Ggf. liegt der Fehler auch an der nicht vorhandenen PHP Version 7.1 bei mir.

Bei Thomas Skerbis läuft das Addon pdfOut 1.3.0 unter PHP Version 7.1 korrekt.

**Comment by skerbis** [comment]
Ja es scheint am Vendor zu liegen

**Comment by skerbis** [comment]
@brandes-webdesign https://github.com/dompdf/dompdf/issues/1559

**Comment by skerbis** [comment]
Wird in dompdf 0.8.2 behoben. Soll in Kürze kommen.

**Comment by skerbis** [comment]
Gefixt: https://github.com/FriendsOfREDAXO/pdfout/releases/tag/1.3.1

**Comment by brandes-webdesign** [comment]
SUPER !!!!!!
DANKE
