### ISSUE TITLE
Teilweise werden Bilder nicht im PDF ausgegeben

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/pdfout#2]

**Comment by staabm** [comment]
konkretes beispiel? liegts an einem bild? wie reproduzieren?

**Comment by olien** [comment]
Hier wird nur das dritte bild richtig ausgegeben:

```
<img src="http:/blupp.de/images/standard/240.jpg" width="250px"> 
<img src="images/standard/240.jpg" width="250px">
<img src="media/240.jpg" alt="" width="250px">
<img src="http://placekitten.com/250/250" width="250px">
```

blupp.de = eigene Domain

**Comment by skerbis** [comment]
media/240.jpg funktioniert , da dompdf über den Servierpfad das Dokument findet. 
Die Urls mit Domain sollten hiermit funktionieren 
`$dompdf->set_option('enable_remote', TRUE);`
Die relative .hatacces - Adresse wird nicht funktionieren

**Comment by skerbis** [comment]
Habe es do gelöst 
`$xpdfcontent = str_replace('<a href="/media/', '<a href="http://domain.xyz/index.php?fileName=', $xpdfcontent);
$xpdfcontent = str_replace("/index.php?rex_media_type=dopic&amp;rex_media_file=", "media/", $xpdfcontent);
$xpdfcontent = str_replace("/media/", "media/", $xpdfcontent);
$xpdfcontent = str_replace("/images/", "media/", $xpdfcontent);
$xpdfcontent = str_replace(".media/", "media/", $xpdfcontent);`

Das deckt die meisten Fälle bei mir ab.
