### ISSUE TITLE
Rename des AddOns zu dompdf

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/pdfout#20]

**Comment by skerbis** [comment]
Wenn du dagegen bist, bleibt es so @olien

**Comment by tbaddade** [comment]
Und nur `pdf` oder `html2pdf`? Also ohne Bezug zur Library.

**Comment by olien** [comment]
Ist mir eigentlich egal ;-)))

**Comment by skerbis** [comment]
@tbaddade html2pdf ist ja eine eigene Library ;-) … Das AddOn liefert aktuell ja nur den vendor dompdf, daher dachte ich, es wäre konsequent es auch so zu nennen. Tatsächlich hat es keine REDAXO-Spezialitäten.  Wenn pdfout weiterhin für Euch passt, bleibt es so.

**Comment by skerbis** [comment]
Bleibt so
