### ISSUE TITLE
PDf wird teilweise im Safari nicht generiert

### ISSUE THREAD

**Issue by lemonhead** [FriendsOfREDAXO/pdfout#21]
Hallo,
ich habe hier ein komisches Phänomen. Die PDFs auf einer Seite werden bei meiner lokalen Version überall super generiert, auch im Safari, bei der Live-Seite geht es allerdings nur in Firefox und Chrome, aber nicht in Safari. Php-Version ist quasi identisch (lokal 7.2.1, live 7.2.8) und die Redaxo und Plugin-Version ist selbstverständlich bei beiden Seiten gleich. Gibt es irgendwelche Server-Konfigurationen, die die Funktion des Plugins derart beeinflussen können, oder habt ihr sonst eine Idee?
Link zu einem PDF auf der Live-Seite: https://www.agentur-jovanovic.de/actresses/theresa-bendel/?pdf=1

**Comment by skerbis** [comment]
wie sieht dein Code aus?

**Comment by lemonhead** [comment]
der Template-Code sieht wiefolgt aus:
`<?php
$pdfcontent = 'REX_ARTICLE[]';
// Outputfilter /sprong
$pdfcontent = rex_extension::registerPoint(new rex_extension_point('OUTPUT_FILTER', $pdfcontent));

// Kopfdefinition
$pre = '
<head>
<style>

@page {
	margin: 40px 0px 20px 0px;
}

@page :first {
    margin-top: 20px;
}

@page:after {
    content: "test";
}

#head-following {
	color: #999999;
	position: fixed;
	height: 20px;
	width: 100%;
	font-size: 10pt;
    left: 60px; 
    right: 60px;
    top: 20px;
    text-align: right;
    z-index: 0;
}

#footer {
	color: #999999;
	position: fixed;
	height: 20px;
	width: 100%;
	font-size: 10pt;
    left: 60px; 
    right: 60px; 
    bottom: 0px;
    text-align: left;
}

body {
    line-height: 1.2em; 
    font-size: 10pt;
    padding: 40px 60px;
}

#logo {
	width: 100%;
	background: #fff;
	z-index: 10;
	position: absolute;
	top: -20px;
	height: 80px;
	padding-top: 20px;
}

a {
    color: #000;
} 

a[href]:after {
    content: " (" attr(href) ")";
    color: #999999;
    font-size: 10pt;
}

h1 {
	font-size: 1.5em; 
	color: #0FABDC; 
	padding-top: 90px; 
	padding-bottom: 0.5em; 
	width: 100%;
	margin: 0;
}

h2, .h2 {
	font-size: 1.3em; 
	color: #0FABDC; 
	padding-bottom: 0.2em; 
	padding-top: 1em;
	clear: both; 
	width: 100%;
	page-break-after: avoid;
	margin: 0;
}

#gallery {
	clear: both;
	width: 100%;
	padding-top: 0;
	padding-bottom: 1em;
}

.galleryUnderline {
	clear: both;
	width: 100%;
	color: #999999;
	font-size: 0.9em;
}

.vita-tables {
	page-break-before:always;
}

.entries {
	clear: both;
}

.entries .row {
	width: 100%;
	clear: both;
	page-break-inside: avoid;
}

.entries .row .vita-label,
.entries .row .info-col { color: #666666; font-size: 0.9em;}
.entries .row .vita-value { color: #000000;}

.entries .row .col {
	display: block;
	width: 120px;
	padding-bottom: 2px;
	float: left;
}

.entries .row .col:first-child {
	width: 75px;
}

.entries .row .col.vita-label {
	width: 110px !important;
}

.entries .row .col.main-col {
	width: 250px;
}

.entries .row .col.vita-value,
.entries .row .col.award-col {
	width: 430px;
}

.additionalInfos {
	width: 100%;
	clear: both;
	padding-top: 2em;
	padding-bottom: 1em;
}

.currentnews,
.furtherMaterial,
.toggleMoreLines,
.big-view,
.galleryUnderline .info {display: none;}

</style>
</head>
<body>
<div id="footer">{{pdf-footer}}</div>
<div id="logo">
<img src="'.rexx::getAbsoluteImageFile("aj_logo.png").'" style="width:280px"; height:auto;"  />
</div>

';
$pre = rex_extension::registerPoint(new rex_extension_point('OUTPUT_FILTER', $pre));


$after = '</body>';
//$after = rex_extension::registerPoint(new rex_extension_point('OUTPUT_FILTER', $after));

/*echo $pre.$pdfcontent;*/
// Dateiname 
$art_pdf_name =  rex_string::normalize(rex_article::getCurrent()->getValue('name'));
header('Content-Type: application/pdf');
$options = new Dompdf\Options();
$options->set('defaultFont', 'Helvetica');
$dompdf = new Dompdf\Dompdf($options);
$dompdf->loadHtml($pre.$pdfcontent.$after);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream($art_pdf_name ,array('Attachment'=>false));
die();

?>`

**Comment by skerbis** [comment]
Füge mal am Anfang 'rex_response::cleanOutputBuffers();' ein und probier mal

**Comment by lemonhead** [comment]
phantastisch! Problem gelöst. Vielen Dank für die schnelle Hilfe.

**Comment by skerbis** [comment]
Ist in der Readme aktualisiert
