### ISSUE TITLE
Beispiel - wie bindet man eigene Webfonts ein

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/pdfout#22]

**Comment by skerbis** [comment]
So wie du es gewohnt bist? Per CSS?

**Comment by skerbis** [comment]
<link rel="stylesheet" href="https://deineDomain.tld/font/fontname.css">

**Comment by tbaddade** [comment]
Hast du mal ein PDF mit den Webfonts erstellt?

Ich binde den Font via @font-face ein. Die Pfade sind relative zu den Fonts. Normales CSS direkt via `<style>`. Fonts greifen aber nicht. Gibt es alternative Libraries?

**Comment by skerbis** [comment]
Schau mal hier: https://github.com/dompdf/dompdf/issues/784
Meine Lösung über link rel oben funktioniert bei mir allerdings.

**Comment by skerbis** [comment]
Hast du in deinem Font-Face ne ttf drin?

**Comment by tbaddade** [comment]
> Hast du in deinem Font-Face ne ttf drin?

Ja.

**Comment by skerbis** [comment]
Ich habe es jetzt auch mal so probier wie du: 

```
@font-face {
  font-family: Lato;
  font-weight: normal;
  font-style: normal;
  src: url("https://domainxy.de/fonts/lato/lato-v14-latin-regular.ttf") format("truetype");
}

body {font-family: "Lato"!important;} 
```

**Comment by skerbis** [comment]
@tbaddade hast du mal n code-Auszug?

**Comment by tbaddade** [comment]
Dompdf interpretiert auch das CSS nicht richtig sauber. Die Library kann man so m.E. nicht wirklich nutzen. Mal sehen wie es in diesem Projekt damit weitergeht. Vielleicht findet sich auch eine Alternative zu Dompdf.

**Comment by skerbis** [comment]
@tbaddade gerne, wenn es eine bessere Library gibt nur her damit. Bei dompdf passiert leider auch nicht mehr viel. Es gab schon lange kein neues Release mehr.
