### ISSUE TITLE
vendor/dompdf via composer.json einbinden

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/pdfout#24]
im projectroot eine composer.json anlegen die die externe library managed.

wenn man dann auf dieses github projekt hier den "dependabot" konfiguriert, bekommt man automatisch einen pull request sobald es neue versionen gibt inkl. deren release notes etc.

https://github.com/marketplace/dependabot

**Comment by skerbis** [comment]
Das ist was für eine spätere Umsetzung, danke ich. Wir sollten prüfen ob dies ein genereller Weg in FOR sein könnte

**Comment by staabm** [comment]
Mit composer umgehen müssten nur die entwickler des addons. 

Für die anwender des addons würde alles so bleiben wie bisher

**Comment by skerbis** [comment]
@staabm, ja das ist klar. Ich meine aktuell hier aber Entwickler.
