### ISSUE TITLE
Call to a member function loadHtml() on null

### ISSUE THREAD

**Issue by crydotsnake** [FriendsOfREDAXO/pdfout#27]
Wenn ich hinter die Url `?pdf=1` Anhänge, kommt der Fehler `Call to a member function loadHtml() on null`. Es wird auf diese Codezeile verwiesen `$dompdf->loadHtml($pdfcontent);`

**Comment by skerbis** [comment]
Ist Inhalt in $pdfcontent?

**Comment by crydotsnake** [comment]
@skerbis Seltsam.. Jetzt geht es aufeinmal.. dann hab ich wieder etwas falsch gemacht ...
