### ISSUE TITLE
Möglichkeit schaffen nicht nur den Content sondern eine ganze Seite (mit Template) als PDF auszugeben

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/pdfout#3]

**Comment by skerbis** [comment]
Funktioniert wunderbar mit `$dompdf->loadHtml('REX_TEMPLATE[XX]');` 
Die Urls zu den Bildern, CSS etc. müssen jedoch ohne vorangestelltem / angegeben werden.
