### ISSUE TITLE
vendor erstellt cache-Dateien im Addon-Verzeichnis

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/pdfout#37]
![image](https://user-images.githubusercontent.com/3855487/78356936-ce0eed00-75b0-11ea-93d1-d044954bb713.png)

![image](https://user-images.githubusercontent.com/3855487/78356941-d23b0a80-75b0-11ea-832e-6a734fcc221a.png)

Diese müssten eigentlich im Cache-Verzeichnis landen.

**Comment by alexplusde** [comment]
Lösungsansatz: in die `install.php`
```
        rex_dir::create(rex_path::addonCache('pdfout', 'fonts'));
```

in dompdf diese Option aktivieren:
```
        $dompdf->set_option('font_cache', rex_path::addonCache('pdfout', 'fonts'));
```

Kann man diese Option irgendwie voreinstellen?

**Comment by skerbis** [comment]
Wir brauchen eine abgeleitete Class. Dann geht's

**Comment by alexplusde** [comment]
Dann wäre ich dafür :)
