### ISSUE TITLE
& statt ?

### ISSUE THREAD

**Issue by TrueHatori** [FriendsOfREDAXO/pdfout#4]
Moin,
kann es sein, dass man mit dem Fragezeichen nicht weit kommt? Bei mir funktioniert der Aufruf als PDF so:
`<a href="index.php?article_id=114&pdf=1">Dieser Artikel als PDF</a>`

Oder mach ich wieder was falsch?

**Comment by olien** [comment]
So ist es bei deiner URL Schreibweise schon richtig...
