### ISSUE TITLE
Eigene Klasse erstellen rex_pdfout und mit Parametern vorbelegen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/pdfout#41]
Um die Doku und den Einsatz zu vereinfachen, sollten wir wie von @skerbis vorgeschlagen eine eigene Klasse machen, die dompdf erweitert und die wichtigsten Einstellungen vorbelegt, die im Praxiseinsatz von Nöten sind, z.B. das korrekte Setzen des Cache-Paths in #40

**Comment by skerbis** [comment]
4.0
