### ISSUE TITLE
Bilder aus media werden nicht mehr gefunden

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/pdfout#45]
In V4.0 werden Bilder, die mit V2.0 noch korrekt in der PDF dargestellt wurden, nicht mehr gefunden.

`media/bild.jpg` wie in der Doku angegeben hat nicht funktioniert, der absolute URL-Pfad `https://domain.de/media/bild.jpg` hat nicht geklappt und ich habe keine relative Kombination wie `/media/bild.jpg` oder `../media/bild.jpg` etc gefunden, mit der es geklappt hat.
Downgrade des Addons auf 2.1.0 hat geholfen. Alle Bilder waren dann wieder da.

Rex 5.12.0

**Comment by skerbis** [comment]
- Hast du deinen alten Code verwendet und nur aktualisiert?
- Ich kann es nicht reproduzieren bei mir sieht's gut alle Bilder werden ausgegeben.

**Comment by skerbis** [comment]
Ich schließe mal. Kann es nicht reproduzieren mit dem aktuellen code
