### ISSUE TITLE
Bild-Ausgabe

### ISSUE THREAD

**Issue by suspa** [FriendsOfREDAXO/pdfout#47]
Ich habe ein Bild/Briefbogen im Hintergrund eingefügt, welches im pdf nicht mit ausgegeben wird.

![grafik](https://user-images.githubusercontent.com/78261880/149666808-238cb205-7940-44a6-82e5-50432c8183e1.png)

**Comment by alxndr-w** [comment]
Siehe auch #45

**Comment by alxndr-w** [comment]
@skerbis 

Die Ausgabe hatte funktioniert vor 2 Jahren, da es jetzt erst auffällt, wissen wir nicht, wann das Problem kam. Die Konfiguration sieht soweit aus wie in den Mindestanforderungen - die JPEG-Datei ist ebenfalls fehlerfrei, keine kruden Media Manager Profile oder sonst etwas auffälliges.

<details>
<summary>System report (REDAXO 5.13.2, PHP 7.4.25, MySQL 5.7.36)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.2     |


| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.25     |
|       OPcache | no         |
|        Xdebug | no         |


| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.36 |
| Character set | utf8         |


| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |


| Request       |                     |
| ------------: | :------------------ |
|       Browser | Chrome/97.0.4692.87 |
|      Protocol | HTTP/1.1            |
|         HTTPS | yes                 |


| Packages                    |             |
| --------------------------: | :---------- |
|                     adminer | 1.9.2       |
|                      backup | 2.8.0       |
|                 be_password | 2.0.0       |
|                    be_style | 3.0.1       |
|         be_style/customizer | 3.0.1       |
|             be_style/redaxo | 3.0.1       |
|                     bloecks | 3.1.1       |
|            bloecks/cutncopy | 3.1.1       |
|              bloecks/status | 3.1.1       |
|                cache_warmup | 3.7.0       |
|                        cke5 | 4.2.2       |
|                     cronjob | 2.8.2       |
|                   developer | 3.9.0       |
|             global_settings | 2.7.1       |
|                     install | 2.9.3       |
|                    markitup | 3.7.1       |
|      markitup/documentation | 1.1.0       |
|                      mblock | 3.2.0       |
|               media_manager | 2.12.1      |
|                   mediapool | 2.11.2      |
|                    metainfo | 2.8.4       |
|                       mform | 6.0.13      |
|                  mform/docs | 1.1         |
|               modulsammlung | 4.15.2      |
|                      pdfout | 4.1.3       |
|                   phpmailer | 2.11.1      |
|                     project | dev         |
|            quick_navigation | 5.2.1       |
|                   redactor2 | 4.2.1       |
|                   structure | 2.13.2      |
|           structure/content | 2.13.2      |
|                       theme | 1.3.3       |
|                    tinymce5 | 1.2.2       |
|                       users | 2.8.2       |
|               xoutputfilter | 3.0.0-beta1 |
|       xoutputfilter/backend | 3.0.0       |
| xoutputfilter/documentation | 1.0.0       |
|      xoutputfilter/frontend | 3.0.0       |
| xoutputfilter/import_export | 3.0.0       |
|                       yform | 3.4.2       |
|                  yform/docs | 3.3.1       |
|                 yform/email | 3.4.2       |
|               yform/manager | 3.4.2       |
|             yform_usability | 1.4         |
|                    yrewrite | 2.8.3       |

</details>

**Comment by suspa** [comment]
Das Problem konnte nun durch die Installation der Version 2.1.0 behoben werden.

**Comment by skerbis** [comment]
Hallo @suspa , Hallo @alxndr-w verwendet ihr denn schon sendPdf() ?

**Comment by alxndr-w** [comment]
Ich vermute nein, @suspa kann das aber sicher überprüfen.

**Comment by suspa** [comment]
Hallo @skerbis , @alxndr-w , was ist sendPdf()? und wo muss ich nachschauen?

**Comment by skerbis** [comment]
Seit 2.1.0 hat sich vieles getan. Das Erzeugen der PDFs funktioniert anders, deshalb habe ich dafür eine Hilfsklasse gebaut. 
PdfOut dafür gibt es die Methode sendPdf, die du an beliebiger Stelle aufrufen kannst. Du bist auch nicht mehr Template gebunden. 

Wie das geht steht in der Readme.

**Comment by skerbis** [comment]
Hier zum testen. 


```php
<?php
$html = '<h1>Test</h1><img src="media/bild.jpg"/>';
if(rex::isFrontend())
{   
PdfOut::sendPdf($name = 'pdf_file', $html, $orientation = 'portrait', $defaultFont ='Courier', $attachment = false, $remoteFiles = true);
} 
else
{
    echo $html;
}

```

**Comment by alxndr-w** [comment]
So wird es aktuell gerendert:
```

                // Alternativ kann auch ein Template geladen werden
                $pdfcontent = $invoice_html->parse('invoice.php');
                // Outputfilter auf Inhalt anwenden, sofern verwendet
                // $pdfcontent = rex_extension::registerPoint(new rex_extension_point('OUTPUT_FILTER', $pdfcontent));
                // Dateiname aus Artikelname erstellen.
                $pdf_filename =  "Rechnung ". $invoice_number . " - " . $registrations[0]['company'];
                // PDF erstellen
                header('Content-Type: application/pdf');
                $dompdf = new Dompdf\Dompdf();
                $dompdf->loadHtml($pdfcontent);
                $dompdf->setPaper('A4', 'portrait');
                // Optionen festlegen
                $dompdf->set_option('defaultFont', 'Arial');
                $dompdf->set_option('dpi', '300');
                // Rendern des PDF
                $dompdf->render();
                // Ausliefern des PDF
        $dompdf->stream($pdf_filename, array('Attachment'=>true)); // bei false wird im Browser angezeigt, true erzwingt download
```

**Comment by suspa** [comment]
<img src="media/rechnung.jpg">

Das Bild liegt auf dem Server und ist weder über den kompletten Link erreichbar gewesen (also mit Protokoll) noch so wie oben.

**Comment by skerbis** [comment]
> noch so wie oben
Wie dann?

**Comment by suspa** [comment]
> > noch so wie oben
> 
> Wie dann?

img src="media/rechnung.jpg"

**Comment by skerbis** [comment]
also doch wie oben 😊
Hmm. Aus meiner Sicht sollte es so funktionieren. (tut es zumindest mit meinem Code hier: https://github.com/FriendsOfREDAXO/pdfout/issues/47#issuecomment-1018446857)

**Comment by suspa** [comment]
> also doch wie oben 😊

ich habe wirklich alles durchprobiert und nach der Reinstallation der Version 2.1 konnte ich "back to the roots"

**Comment by alxndr-w** [comment]
Okay, passt. Bei uns ist es hinten angestellt, es funktioniert ja aktuell für uns. Nach dem Update schaue ich mir das nochmal genauer an und werde berichten
