### ISSUE TITLE
Wunsch: savePdf()

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/pdfout#49]
Analog zu `sendPdf();` würde ich mich z.B.  über ein
`savePdf($name = 'pdf_file', $html = '',  $path = "pfad/auf/dem/server/");`
freuen

**Comment by alxndr-w** [comment]
diese Methode ist noch nicht dokumentiert

**Comment by skerbis** [comment]
@alxndr-w leg los

**Comment by skerbis** [comment]
@alxndr-w  @danspringer  Danke ... wird in 7.0.0 besser sein und dokumentiert sein

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/pdfout/releases/tag/7.0.0
