### ISSUE TITLE
DPI auf 300 setzen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/pdfout#55]
In der README ist von 300dpi die Rede, hier wird 100 verwendet

https://github.com/FriendsOfREDAXO/pdfout/blob/6db81231dbf24b5c51a670a00049faab134055f7/lib/pdfout.php#L16

**Comment by skerbis** [comment]
Nein, hatten wir schon mal es sorgte bei einigen Leuten für extrem große PDF und sogar Laufzeitproblemen. 
Ich werde prüfen ob man es übergeben kann.

**Comment by skerbis** [comment]
@alxndr-w wird in 7.0.0 möglich sein
