### ISSUE TITLE
cmap-Dateien deaktivieren

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/pdfout#62]
**Description / Beschreibung**
Ich benötige kein DomPDF - ich finde die Browser machen da inzwischen einen richtig guten Job in der Darstellung von PDFs.

Trotzdem ist mein Backup und mein assets-Ordner jetzt zugemüllt mit diesen Dateien:

![image](https://user-images.githubusercontent.com/3855487/221371816-a065f8db-6cef-43d9-86d5-75ad6ee6b2c5.png)

Wäre es stattdessen möglich, diese in den Cache-Ordner zu legen? Es handelt sich doch hierbei um eine Art von Cache-Dateien, oder?

**Affected versions / Verwendete Versionen**

REDAXO: 
PHP:
Database:
Browser: 
AddOns:

**Did it whoops? / Whoops erhalten?**

**Comment by skerbis** [comment]
Die Files werden vom Viewer benötigt. Ich muss checken ob sie in einem anderen Ordner liegen können.

**Comment by skerbis** [comment]
entfernt

**Comment by alxndr-w** [comment]
Danke!
