### ISSUE TITLE
Error im Installer: Die Prüfsumme der heruntergeladenen Zip-Datei stimmt nicht mit der erwarteten überein!

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/pdfout#7]
Der Installer meckert:

> AddOn "pdfout" konnte aus folgendem Grund nicht aktualisiert werden:
Die Prüfsumme der heruntergeladenen Zip-Datei stimmt nicht mit der erwarteten überein!

**Comment by skerbis** [comment]
@isospin sollte behoben sein. Bitte testen.

**Comment by isospin** [comment]
problem behoben!
