### ISSUE TITLE
Warum dompdf in assets

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/pdfout#9]
Warum wird die Lib bei der Installation in den Root-Assets-Ordner kopiert, und dann von dort geladen?

Der Assets-Ordner ist eigentlich nicht für PHP-Dateien gedacht, insbesondere da er nicht vor dem direkten Aufruf geschützt ist.

**Comment by olien** [comment]
Wo sollen solche Dateien am besten hin?

**Comment by gharlan** [comment]
Dort, wie sie auch aktuell liegen, in `vendor`. Also gar nicht verschieben.

**Comment by olien** [comment]
ok. danke... 

->  @skerbis :-)

**Comment by skerbis** [comment]
Wollte ich als nächstes angehen @olien

**Comment by skerbis** [comment]
done
